apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-webnginx
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-webnginx
      app.kubernetes.io/name: gitopswebnginx
      name: mynginx
  template:
    metadata:
      labels:
        app: gitops-webnginx
        app.kubernetes.io/name: gitopswebnginx
        name: mynginx
    spec:
      containers:
      - image: iamraj007/my-nginx:v2
        name: gitops-webpod
        ports:
        - containerPort: 80
          protocol: TCP
