apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitops-webnginx
  name: gitops-webnginx-svc
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 5050
  selector:
    app: gitops-webnginx
